jobs:
  build:
    docker:
      - image: 'node:14'
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: npm i && npm run build
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.0
version: 2.1
workflows:
  main:
    jobs:
      - build:
          context: sonarcloud