version: 2.1

jobs:
  build:
    docker:
      - image: mhart/alpine-node:14
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: npm i && npm run build
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud